### ISSUE TITLE
drop is_mocked_foo from mock decorator

### ISSUE THREAD

**Issue by alunduil** [kumoru/torment#21]
I'd rather encourage users to use the call they create rather than rely on a property that may or may not exist after that function is called.  This will provide a better experience.

**Comment by alunduil** [comment]
Turns out the call itself uses this property to determine if it should re-invoke the mocking call.  I'd still prefer a world without this property but for now we should just encourage users to not use it rather than removing it.  We could move it to a private property if we like, what's the vote on that?

**Comment by dubsquared** [comment]
I feel like in order to make the code more readable and easier to debug, using the created call will help eliminate unsuspected error cases.  This could remove a lot of dependency rabbit hole checking, so the private property idea seems legit.  If can be used if or when necessary, but not make it a dependent property.
